---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-delete
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.20.200.67
  share: /kuber_nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  #- hard
  - nconnect=8
  - nfsvers=3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-retain
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.20.200.67
  share: /kuber_nfs
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  #- hard
  - nconnect=8
  - nfsvers=3
