---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gophish-config
  namespace: netsecapp
data:
  config: |
    {
      "admin_server": {
        "listen_url": "0.0.0.0:3333",
        "use_tls": false,
        "cert_path": "gophish_admin.crt",
        "key_path": "gophish_admin.key"
      },
      "phish_server": {
        "listen_url": "0.0.0.0:8080",
        "use_tls": false,
        "cert_path": "example.crt",
        "key_path": "example.key"
      },
      "db_name": "mysql",
      "db_path": "phishadmin:tqt4jy!r7usdwYS@(mysql-standalone-0.mysql-standalone.netsecdb.svc.cluster.local:3306)/gophish?charset=utf8&parseTime=True&loc=UTC",
      "migrations_prefix": "db/db_",
      "contact_address": "satyanu chattergy",
      "logging": {
        "filename": "",
        "level": ""
      }
    }
