---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gophish-config
  namespace: netsec
data:
  config: |
    {
      "admin_server": {
        "listen_url": "0.0.0.0:3333",
        "use_tls": false,
        "cert_path": "gophish_admin.crt",
        "key_path": "gophish_admin.key"
      },
      "phish_server": {
        "listen_url": "0.0.0.0:8080",
        "use_tls": false,
        "cert_path": "example.crt",
        "key_path": "example.key"
      },
      "db_name": "mysql",
      "db_path": "gophish:gop_2022@(192.168.101.75:1527)/testodia?charset=utf8&parseTime=True&loc=UTC",
      "migrations_prefix": "db/db_",
      "contact_address": "satyanu chattergy",
      "logging": {
        "filename": "",
        "level": ""
      }
    }
