apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: netsecdb
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: d9yHA!BsfY5gZ7@
  MYSQL_DATABASE: gophish
  MYSQL_USER: phishadmin
  MYSQL_PASSWORD: tqt4jy!r7usdwYS
